# Generated by Django 4.2.2 on 2023-07-01 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Eintrag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ueberschrift', models.CharField(max_length=50, verbose_name='Überschrift')),
                ('slug', models.SlugField(verbose_name='Schlagwort')),
                ('text', models.TextField(verbose_name='Eintrag')),
                ('erstellt', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt')),
                ('geaendert', models.DateTimeField(auto_now=True, verbose_name='Geändert')),
                ('aktiv', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Verfasser')),
            ],
            options={
                'verbose_name': 'Eintrag',
                'verbose_name_plural': 'Einträge',
            },
        ),
    ]
