# Generated by Django 4.2.2 on 2023-07-01 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eintrag',
            options={'ordering': ['-geaendert'], 'verbose_name': 'Eintrag', 'verbose_name_plural': 'Einträge'},
        ),
    ]
