# Generated by Django 4.2.2 on 2023-07-01 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0002_alter_eintrag_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kommentar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bewertung', models.IntegerField(verbose_name='Bewertung')),
                ('slug', models.SlugField(verbose_name='Schlagwort')),
                ('kommentar', models.TextField(verbose_name='Kommentar')),
                ('erstellt', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt')),
                ('geaendert', models.DateTimeField(auto_now=True, verbose_name='Geändert')),
                ('aktiv', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('eintrag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.eintrag', verbose_name='Blog-Eintrag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Verfasser')),
            ],
            options={
                'verbose_name': 'Kommentar',
                'verbose_name_plural': 'Kommentare',
                'ordering': ['user', '-geaendert'],
            },
        ),
    ]
