# Generated by Django 4.2.2 on 2023-07-18 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_kommentar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Bezeichnung')),
                ('source', models.CharField(max_length=50, verbose_name='Quelle')),
                ('ursprung', models.CharField(max_length=50, verbose_name='Ursprung')),
                ('ort', models.CharField(max_length=50, verbose_name='Ort der Aufnahme')),
                ('fotograf', models.CharField(max_length=50, verbose_name='Fotograph')),
            ],
            options={
                'verbose_name': 'Bild',
                'verbose_name_plural': 'Bilder',
            },
        ),
    ]
