# Generated by Django 4.2.2 on 2023-07-11 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_eintrag_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eintrag',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Schlagwort'),
        ),
    ]
